# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:54
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    """Creates the groups "Content managers" and "Social users"."""

    # We can't import the models directly as they may be newer versions than this migration expects.
    # We use the historical versions instead.
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    UserSocialAuth = apps.get_model('social_auth', 'UserSocialAuth')

    db_alias = schema_editor.connection.alias

    perm_manage = Permission.objects.using(db_alias).get(name='Manage curriculum')
    perm_consume = Permission.objects.using(db_alias).get(name='Consume curriculum')

    manager_group = Group.objects.using(db_alias).create(name='Content managers')
    socialuser_group = Group.objects.using(db_alias).create(name='Social users')

    manager_group.permissions.add(perm_manage)
    socialuser_group.permissions.add(perm_consume)

    for socialuser in UserSocialAuth.objects.all():
        socialuser.user.groups.add(socialuser_group)


def reverse_func(apps, schema_editor):
    """Deletes the groups "Content managers" and "Social users"."""
    Group = apps.get_model('auth', 'Group')
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name='Content managers').delete()
    Group.objects.using(db_alias).filter(name='Social users').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('socialusers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
