# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_minimum', models.PositiveSmallIntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
