# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_surveys', to=settings.AUTH_USER_MODEL),
        ),
    ]
